spring:
  config:
    activate:
      on-profile: prod
    import: optional:aws-secretsmanager:${AWS_SECRET_ID:buddystudy/prod}
  r2dbc:
    url: ${R2DBC_DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}
  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      secretsmanager:
        enabled: ${SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED:false}
        region: ${AWS_REGION:ap-northeast-2}

buddystudy:
  logging:
    api:
      detail: ${API_LOG_DETAIL:detailed}
  scheduler:
    enabled: ${SCHEDULER_ENABLED:true}
  streams:
    enabled: ${BUDDYSTUDY_STREAMS_ENABLED:true}
  openapi:
    enabled: ${ENABLE_OPENAPI_DOCS:false}
    access-token: ${OPENAPI_ACCESS_TOKEN:}
