spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/buddystuddy}
    username: ${DATABASE_USERNAME:buddystuddy}
    password: ${DATABASE_PASSWORD:local-password}
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

buddystuddy:
  scheduler:
    enabled: ${SCHEDULER_ENABLED:false}
  streams:
    enabled: ${REACTION_STREAM_ENABLED:false}
  openapi:
    enabled: ${ENABLE_OPENAPI_DOCS:true}
    access-token: ${OPENAPI_ACCESS_TOKEN:local-openapi}
