package com.buddystudy.backend

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.boot.test.web.server.LocalServerPort
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.test.context.TestPropertySource
import java.net.URI
import java.net.http.HttpClient
import java.net.http.HttpRequest
import java.net.http.HttpResponse
import java.sql.Timestamp
import java.time.Instant

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestPropertySource(
    properties = [
        "spring.datasource.url=jdbc:h2:mem:buddystudy-admin-scheduler-status;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.jpa.hibernate.ddl-auto=create-drop",
        "spring.flyway.enabled=false",
        "buddystudy.scheduler.enabled=false",
        "buddystudy.streams.enabled=false",
        "buddystudy.crypto.master-key=test-master-key",
        "buddystudy.auth.jwt-secret=test-jwt-secret",
        "buddystudy.admin.username=admin",
        "buddystudy.admin.password=admin",
        "buddystudy.monitoring.scheduler-stale-threshold-minutes=15",
        "buddystudy.monitoring.scheduler-monitored-jobs=question-schedule,user-stats-refresh",
        "spring.autoconfigure.exclude=com.redisstream.RedisStreamCoordinatorAutoConfiguration,com.redisstream.producer.ProducerRoutingAutoConfiguration,com.redisstream.consumer.CoordinatorConsumerAutoConfiguration",
    ],
)
class AdminSchedulerStatusIntegrationTest {
    @Autowired lateinit var jdbc: JdbcTemplate
    @Autowired lateinit var mapper: ObjectMapper
    @LocalServerPort var port: Int = 0

    private val client = HttpClient.newHttpClient()

    @BeforeEach
    fun setUpSchema() {
        jdbc.execute(
            """
            create table if not exists scheduled_jobs (
                job_name varchar(120) primary key,
                enabled boolean not null default true,
                schedule_type varchar(40) not null,
                schedule_value varchar(120) not null,
                max_retry_count integer not null default 3,
                timeout_seconds integer not null default 300,
                lock_seconds integer not null default 300,
                created_at timestamp not null default current_timestamp,
                updated_at timestamp not null default current_timestamp
            )
            """.trimIndent(),
        )
        jdbc.execute(
            """
            create table if not exists scheduled_job_runs (
                id bigint generated by default as identity primary key,
                job_name varchar(120) not null,
                trigger_type varchar(40) not null,
                status varchar(40) not null,
                started_at timestamp not null,
                finished_at timestamp null,
                duration_ms bigint null,
                summary varchar(500) null,
                error_message varchar(1000) null,
                retry_of_run_id bigint null,
                created_by varchar(120) not null,
                created_at timestamp not null default current_timestamp
            )
            """.trimIndent(),
        )
        jdbc.update("delete from scheduled_job_runs")
        jdbc.update("delete from scheduled_jobs")
        jdbc.update(
            """
            insert into scheduled_jobs (job_name, enabled, schedule_type, schedule_value)
            values
                ('question-schedule', true, 'FIXED_DELAY', '30s'),
                ('user-stats-refresh', true, 'CRON', '0 */5 * * * *')
            """.trimIndent(),
        )
        jdbc.update(
            """
            insert into scheduled_job_runs (
                job_name, trigger_type, status, started_at, finished_at, duration_ms, summary, created_by
            ) values (?, 'SCHEDULED', 'SUCCESS', ?, ?, 12, 'created=3', 'system')
            """.trimIndent(),
            "question-schedule",
            Timestamp.from(Instant.now()),
            Timestamp.from(Instant.now()),
        )
        jdbc.update(
            """
            insert into scheduled_job_runs (
                job_name, trigger_type, status, started_at, finished_at, duration_ms, error_message, created_by
            ) values (?, 'SCHEDULED', 'FAILED', ?, ?, 18, 'aggregation failed', 'system')
            """.trimIndent(),
            "user-stats-refresh",
            Timestamp.from(Instant.now()),
            Timestamp.from(Instant.now()),
        )
    }

    @Test
    fun `admin can inspect scheduler statuses through HTTP`() {
        val token = loginAdmin()

        val response = get("/api/v1/admin/jobs/statuses", token)

        assertThat(response.statusCode()).isEqualTo(200)
        val body = response.json()
        assertThat(body["jobs"]).hasSize(2)
        val questionSchedule = body["jobs"].first { it["jobName"].asText() == "question-schedule" }
        val statsRefresh = body["jobs"].first { it["jobName"].asText() == "user-stats-refresh" }
        assertThat(questionSchedule["enabled"].asBoolean()).isTrue()
        assertThat(questionSchedule["stale"].asBoolean()).isFalse()
        assertThat(questionSchedule["latestRun"]["status"].asText()).isEqualTo("SUCCESS")
        assertThat(statsRefresh["stale"].asBoolean()).isTrue()
        assertThat(statsRefresh["latestRun"]["status"].asText()).isEqualTo("FAILED")
        assertThat(statsRefresh["latestRun"]["errorMessage"].asText()).isEqualTo("aggregation failed")
    }

    @Test
    fun `admin can page scheduler run history through HTTP`() {
        val token = loginAdmin()

        val response = get("/api/v1/admin/jobs/runs?jobName=%20%20%20&limit=1&offset=0", token)

        assertThat(response.statusCode()).isEqualTo(200)
        val body = response.json()
        assertThat(body["runs"]).hasSize(1)
        assertThat(body["totalCount"].asLong()).isEqualTo(2)
        assertThat(body["limit"].asInt()).isEqualTo(1)
        assertThat(body["offset"].asInt()).isEqualTo(0)
        assertThat(body["runs"][0]["jobName"].asText()).isIn("question-schedule", "user-stats-refresh")
    }

    @Test
    fun `scheduler run history requires admin token`() {
        val response = get("/api/v1/admin/jobs/runs", bearerToken = null)

        assertThat(response.statusCode()).isEqualTo(401)
        assertThat(response.body()).contains("AUTH_INVALID_ACCESS_TOKEN")
    }

    @Test
    fun `admin metrics require admin token`() {
        val response = get("/api/v1/admin/analytics/metrics?startDate=2026-01-01&endDate=2026-01-02", bearerToken = null)

        assertThat(response.statusCode()).isEqualTo(401)
        assertThat(response.body()).contains("AUTH_INVALID_ACCESS_TOKEN")
    }

    @Test
    fun `admin analytics refresh requires admin token`() {
        val response = post("/api/v1/admin/analytics/refresh?startDate=2026-01-01&endDate=2026-01-02", "", bearerToken = null)

        assertThat(response.statusCode()).isEqualTo(401)
        assertThat(response.body()).contains("AUTH_INVALID_ACCESS_TOKEN")
    }

    @Test
    fun `scheduler retry requires admin token`() {
        val response = post("/api/v1/admin/jobs/question-schedule/retry", "", bearerToken = null)

        assertThat(response.statusCode()).isEqualTo(401)
        assertThat(response.body()).contains("AUTH_INVALID_ACCESS_TOKEN")
    }

    @Test
    fun `admin can see monitored scheduler jobs missing from seed table`() {
        jdbc.update("delete from scheduled_job_runs where job_name = 'user-stats-refresh'")
        jdbc.update("delete from scheduled_jobs where job_name = 'user-stats-refresh'")
        val token = loginAdmin()

        val response = get("/api/v1/admin/jobs/statuses", token)

        assertThat(response.statusCode()).isEqualTo(200)
        val missing = response.json()["jobs"].first { it["jobName"].asText() == "user-stats-refresh" }
        assertThat(missing["enabled"].asBoolean()).isTrue()
        assertThat(missing["scheduleType"].asText()).isEqualTo("MISSING")
        assertThat(missing["scheduleValue"].asText()).isEqualTo("not seeded")
        assertThat(missing["stale"].asBoolean()).isTrue()
        assertThat(missing["latestRun"].isNull).isTrue()
    }

    @Test
    fun `scheduler statuses require admin token`() {
        val response = get("/api/v1/admin/jobs/statuses", bearerToken = null)

        assertThat(response.statusCode()).isEqualTo(401)
        assertThat(response.body()).contains("AUTH_INVALID_ACCESS_TOKEN")
    }

    private fun loginAdmin(): String {
        val response = post(
            "/api/v1/admin/login",
            """{"username":"admin","password":"admin"}""",
            bearerToken = null,
        )
        assertThat(response.statusCode()).isEqualTo(200)
        return response.json()["adminToken"].asText()
    }

    private fun get(path: String, bearerToken: String?): HttpResponse<String> {
        val builder = HttpRequest.newBuilder(URI.create("http://127.0.0.1:$port$path")).GET()
        if (!bearerToken.isNullOrBlank()) {
            builder.header("Authorization", "Bearer $bearerToken")
        }
        return client.send(builder.build(), HttpResponse.BodyHandlers.ofString())
    }

    private fun post(path: String, body: String, bearerToken: String?): HttpResponse<String> {
        val builder = HttpRequest.newBuilder(URI.create("http://127.0.0.1:$port$path"))
            .header("Content-Type", "application/json")
            .POST(HttpRequest.BodyPublishers.ofString(body))
        if (!bearerToken.isNullOrBlank()) {
            builder.header("Authorization", "Bearer $bearerToken")
        }
        return client.send(builder.build(), HttpResponse.BodyHandlers.ofString())
    }

    private fun HttpResponse<String>.json(): JsonNode = mapper.readTree(body())
}
