apiVersion: v1
kind: ConfigMap
metadata:
  name: buddystuddy-backend-config
data:
  APP_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CLOUD_AWS_SECRETSMANAGER_ENABLED: "false"
  FLYWAY_LOCATIONS: "filesystem:/app/db/migration"
  DATABASE_URL: "jdbc:postgresql://buddystuddy-postgres:5432/buddystuddy"
  DATABASE_USERNAME: "buddystuddy"
  ADMIN_ANALYTICS_DATABASE_URL: "jdbc:postgresql://buddystuddy-postgres:5432/buddystuddy_aggregation"
  ADMIN_ANALYTICS_DATABASE_USERNAME: "buddystuddy"
  REDIS_HOST: "buddystuddy-redis"
  REDIS_PORT: "6379"
  REDIS_SSL: "false"
  ENABLE_OPENAPI_DOCS: "false"
  SCHEDULER_ENABLED: "true"
  SCHEDULER_BATCH_SIZE: "50"
  MAX_PENDING_PER_STUDY: "1"
  REACTION_STREAM_ENABLED: "true"
  REACTION_STREAM_COORDINATOR_BASE_URL: "https://coordinator.ghkdqhrbals.org"
  REACTION_STREAM_COORDINATOR_USERNAME: "admin"
  PUSH_STREAM_PREFIX: "push-v1"
  VIEW_STREAM_PREFIX: "view-v1"
  BUDDYSTUDDY_TRANSLATION_BASE_URL: "http://buddystuddy-libretranslate:5000"
  GOOGLE_IOS_CLIENT_ID: "328281669925-evuebplih3vir99daj4lapj1javqsmsr.apps.googleusercontent.com"
