alter table devices add column app_version varchar(64);
alter table devices add column app_build varchar(64);
alter table devices add column app_version_seen_at timestamp;
create index idx_devices_user_app_version_seen on devices(user_id, app_version_seen_at, id);

create table app_update_campaigns (
    id bigint generated by default as identity primary key,
    platform varchar(32) not null,
    target_version varchar(64) not null,
    target_build varchar(64) not null,
    update_mode varchar(16) not null,
    title_ko varchar(255) not null,
    title_en varchar(255) not null,
    title_ja varchar(255) not null,
    message_ko clob not null,
    message_en clob not null,
    message_ja clob not null,
    app_store_url varchar(1024) not null,
    status varchar(16) not null,
    created_by varchar(191) not null,
    activated_at timestamp not null,
    ended_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);
create index idx_app_update_campaigns_active on app_update_campaigns(platform, status, activated_at, id);

create table app_update_user_states (
    campaign_id bigint not null,
    user_id bigint not null,
    device_id varchar(191) not null,
    first_version varchar(64) not null,
    first_build varchar(64) not null,
    current_version varchar(64) not null,
    current_build varchar(64) not null,
    first_checked_at timestamp not null,
    last_checked_at timestamp not null,
    prompted_at timestamp,
    dismissed_at timestamp,
    app_store_opened_at timestamp,
    converted_at timestamp,
    primary key (campaign_id, user_id)
);
create index idx_app_update_states_campaign_conversion on app_update_user_states(campaign_id, converted_at, prompted_at);
create index idx_app_update_states_user_checked on app_update_user_states(user_id, last_checked_at);
