alter table app_update_campaigns add column remote_config_status varchar(16) default 'PENDING' not null;
alter table app_update_campaigns add column remote_config_revision bigint;
alter table app_update_campaigns add column remote_config_published_at timestamp;
alter table app_update_campaigns add column remote_config_error varchar(1000);
create index idx_app_update_remote_config on app_update_campaigns(remote_config_status, remote_config_published_at, id);

create table app_control_events (
    id bigint generated by default as identity primary key,
    event_id varchar(191) not null unique,
    user_id bigint not null,
    device_id varchar(191) not null,
    event_type varchar(32) not null,
    platform varchar(32) not null,
    distribution_channel varchar(32) not null,
    app_version varchar(64) not null,
    app_build varchar(64) not null,
    policy_id varchar(191),
    policy_revision bigint,
    campaign_id bigint,
    evaluated_action varchar(64),
    occurred_at timestamp not null,
    recorded_at timestamp not null
);
create index idx_app_control_events_device on app_control_events(device_id, recorded_at, id);
create index idx_app_control_events_user on app_control_events(user_id, recorded_at, id);
create index idx_app_control_events_campaign on app_control_events(campaign_id, event_type, recorded_at);

create table app_control_maintenance_windows (
    id bigint generated by default as identity primary key,
    starts_at timestamp not null,
    ends_at timestamp,
    title_ko varchar(255) not null,
    title_en varchar(255) not null,
    title_ja varchar(255) not null,
    message_ko clob not null,
    message_en clob not null,
    message_ja clob not null,
    status varchar(16) not null,
    created_by varchar(191) not null,
    terminated_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null
);
create index idx_app_control_maintenance_active on app_control_maintenance_windows(status, starts_at, ends_at, id);
