package com.buddystudy.backend.auth.adapter.outbound.persistence

import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.DatabaseClient
import java.time.Instant

class PermissionPolicyPersistenceAdapterTest {
    private val client = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///notification-preferences;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1"),
    )
    private val adapter = PermissionPolicyPersistenceAdapter(client)

    @BeforeEach
    fun setUpSchema(): Unit = runBlocking {
        execute(
            """
            create table if not exists notification_preferences (
                id bigint generated by default as identity primary key,
                user_id bigint null,
                device_id varchar(191) null,
                preference_key varchar(120) not null,
                enabled boolean not null,
                created_at timestamp not null,
                updated_at timestamp not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists users (
                id bigint primary key,
                created_at timestamp not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists user_membership_tiers (
                tier_code varchar(32) primary key,
                monthly_question_limit integer not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists user_quota (
                user_id bigint primary key,
                anchor_at timestamp not null,
                period_started_at timestamp not null,
                period_ends_at timestamp not null,
                base_limit integer not null,
                bonus_limit integer not null,
                committed_count integer not null,
                reserved_count integer not null
            )
            """.trimIndent(),
        )
        execute("delete from notification_preferences")
        execute("delete from user_quota")
        execute("delete from user_membership_tiers")
        execute("delete from users")
    }

    @Test
    fun `question notifications default to enabled for signed in users`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isTrue()
    }

    @Test
    fun `notification defaults remain disabled for anonymous and marketing subjects`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(null, "dev-1", "question_notification")).isFalse()
        assertThat(adapter.isEnabled(7, "dev-1", "marketing_notification")).isFalse()
    }

    @Test
    fun `stored question notification opt out overrides signed in default`(): Unit = runBlocking {
        execute(
            """
            insert into notification_preferences
                (user_id, device_id, preference_key, enabled, created_at, updated_at)
            values (7, 'dev-1', 'question_notification', false, current_timestamp, current_timestamp)
            """.trimIndent(),
        )

        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isFalse()
    }

    @Test
    fun `quota lookup reads the current user quota row including reserved questions`(): Unit = runBlocking {
        execute("insert into users (id, created_at) values (7, timestamp '2026-01-07 12:34:56')")
        execute("insert into user_membership_tiers (tier_code, monthly_question_limit) values ('TIER1', 30)")
        execute(
            """
            insert into user_quota (
                user_id, anchor_at, period_started_at, period_ends_at,
                base_limit, bonus_limit, committed_count, reserved_count
            ) values (
                7, timestamp '2026-01-07 12:34:56',
                timestamp '2026-07-07 12:34:56', timestamp '2026-08-07 12:34:56',
                30, 5, 12, 3
            )
            """.trimIndent(),
        )

        val status = adapter.status(
            userId = 7,
            key = "monthly_question",
            now = Instant.parse("2026-08-01T00:00:00Z"),
        )

        assertThat(status.remaining).isEqualTo(20)
        assertThat(status.periodStartedAt).isEqualTo(Instant.parse("2026-07-07T12:34:56Z"))
        assertThat(status.resetAt).isEqualTo(Instant.parse("2026-08-07T12:34:56Z"))
    }

    @Test
    fun `overdue user quota row falls back to a fresh anchored period without old counters`() = runBlocking {
        execute("insert into users (id, created_at) values (7, timestamp '2026-01-07 12:34:56')")
        execute("insert into user_membership_tiers (tier_code, monthly_question_limit) values ('TIER1', 30)")
        execute(
            """
            insert into user_quota (
                user_id, anchor_at, period_started_at, period_ends_at,
                base_limit, bonus_limit, committed_count, reserved_count
            ) values (
                7, timestamp '2026-01-07 12:34:56',
                timestamp '2026-07-07 12:34:56', timestamp '2026-08-07 12:34:56',
                30, 8, 29, 1
            )
            """.trimIndent(),
        )

        val status = adapter.status(
            userId = 7,
            key = "monthly_question",
            now = Instant.parse("2026-08-08T00:00:00Z"),
        )

        assertThat(status.remaining).isEqualTo(30)
        assertThat(status.periodStartedAt).isEqualTo(Instant.parse("2026-08-07T12:34:56Z"))
        assertThat(status.resetAt).isEqualTo(Instant.parse("2026-09-07T12:34:56Z"))
    }

    @Test
    fun `missing current quota row uses the free tier for the anchored period`() = runBlocking {
        execute("insert into users (id, created_at) values (7, timestamp '2026-01-31 12:34:56')")
        execute("insert into user_membership_tiers (tier_code, monthly_question_limit) values ('TIER1', 30)")

        val status = adapter.status(
            userId = 7,
            key = "monthly_question",
            now = Instant.parse("2026-02-10T00:00:00Z"),
        )

        assertThat(status.remaining).isEqualTo(30)
        assertThat(status.periodStartedAt).isEqualTo(Instant.parse("2026-01-31T12:34:56Z"))
        assertThat(status.resetAt).isEqualTo(Instant.parse("2026-02-28T12:34:56Z"))
    }

    private suspend fun execute(sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }
}
