package com.buddystudy.backend.auth.adapter.outbound.persistence

import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.DatabaseClient

class PermissionPolicyPersistenceAdapterTest {
    private val client = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///notification-preferences;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1"),
    )
    private val adapter = PermissionPolicyPersistenceAdapter(client)

    @BeforeEach
    fun setUpSchema(): Unit = runBlocking {
        execute(
            """
            create table if not exists notification_preferences (
                id bigint generated by default as identity primary key,
                user_id bigint null,
                device_id varchar(191) null,
                preference_key varchar(120) not null,
                enabled boolean not null,
                created_at timestamp not null,
                updated_at timestamp not null
            )
            """.trimIndent(),
        )
        execute("delete from notification_preferences")
    }

    @Test
    fun `question notifications default to enabled for signed in users`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isTrue()
    }

    @Test
    fun `notification defaults remain disabled for anonymous and marketing subjects`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(null, "dev-1", "question_notification")).isFalse()
        assertThat(adapter.isEnabled(7, "dev-1", "marketing_notification")).isFalse()
    }

    @Test
    fun `stored question notification opt out overrides signed in default`(): Unit = runBlocking {
        execute(
            """
            insert into notification_preferences
                (user_id, device_id, preference_key, enabled, created_at, updated_at)
            values (7, 'dev-1', 'question_notification', false, current_timestamp, current_timestamp)
            """.trimIndent(),
        )

        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isFalse()
    }

    private suspend fun execute(sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }
}
