package com.buddystudy.backend.auth.adapter.outbound.persistence

import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.DatabaseClient
import java.time.Instant

class PermissionPolicyPersistenceAdapterTest {
    private val client = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///notification-preferences;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1"),
    )
    private val adapter = PermissionPolicyPersistenceAdapter(client)

    @BeforeEach
    fun setUpSchema(): Unit = runBlocking {
        execute(
            """
            create table if not exists notification_preferences (
                id bigint generated by default as identity primary key,
                user_id bigint null,
                device_id varchar(191) null,
                preference_key varchar(120) not null,
                enabled boolean not null,
                created_at timestamp not null,
                updated_at timestamp not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists users (
                id bigint primary key,
                created_at timestamp not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists user_membership_tiers (
                tier_code varchar(32) primary key,
                monthly_question_limit integer not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists user_memberships (
                id bigint generated by default as identity primary key,
                user_id bigint not null,
                tier varchar(32) not null,
                status varchar(32) not null,
                expires_at timestamp null,
                updated_at timestamp not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists user_monthly_question_usage (
                id bigint generated by default as identity primary key,
                user_id bigint not null,
                usage_month varchar(7) not null,
                period_start timestamp not null,
                system_question_count integer not null
            )
            """.trimIndent(),
        )
        execute("delete from notification_preferences")
        execute("delete from user_monthly_question_usage")
        execute("delete from user_memberships")
        execute("delete from user_membership_tiers")
        execute("delete from users")
    }

    @Test
    fun `question notifications default to enabled for signed in users`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isTrue()
    }

    @Test
    fun `notification defaults remain disabled for anonymous and marketing subjects`(): Unit = runBlocking {
        assertThat(adapter.isEnabled(null, "dev-1", "question_notification")).isFalse()
        assertThat(adapter.isEnabled(7, "dev-1", "marketing_notification")).isFalse()
    }

    @Test
    fun `stored question notification opt out overrides signed in default`(): Unit = runBlocking {
        execute(
            """
            insert into notification_preferences
                (user_id, device_id, preference_key, enabled, created_at, updated_at)
            values (7, 'dev-1', 'question_notification', false, current_timestamp, current_timestamp)
            """.trimIndent(),
        )

        assertThat(adapter.isEnabled(7, "dev-1", "question_notification")).isFalse()
    }

    @Test
    fun `quota lookup keeps usage until the users signup anniversary`(): Unit = runBlocking {
        execute("insert into users (id, created_at) values (7, timestamp '2026-01-07 12:34:56')")
        execute("insert into user_membership_tiers (tier_code, monthly_question_limit) values ('TIER1', 30)")
        execute(
            """
            insert into user_monthly_question_usage (user_id, usage_month, period_start, system_question_count)
            values (7, '2026-07', timestamp '2026-07-07 12:34:56', 12)
            """.trimIndent(),
        )

        val status = adapter.status(
            userId = 7,
            key = "monthly_question",
            now = Instant.parse("2026-08-01T00:00:00Z"),
        )

        assertThat(status.remaining).isEqualTo(18)
        assertThat(status.periodStartedAt).isEqualTo(Instant.parse("2026-07-07T12:34:56Z"))
        assertThat(status.resetAt).isEqualTo(Instant.parse("2026-08-07T12:34:56Z"))
    }

    private suspend fun execute(sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }
}
