create table external_api_call_history (
    id bigint not null auto_increment,
    call_id char(36) not null,
    correlation_id varchar(255) null,
    provider varchar(64) not null,
    operation varchar(128) not null,
    http_method varchar(16) not null,
    request_url text not null,
    request_headers_json longtext not null,
    request_body longtext null,
    response_status int null,
    response_headers_json longtext null,
    response_body longtext null,
    status varchar(32) not null,
    error_type varchar(255) null,
    error_message longtext null,
    started_at datetime(6) not null,
    finished_at datetime(6) null,
    duration_ms bigint null,
    created_at datetime(6) not null,
    updated_at datetime(6) not null,
    primary key (id),
    unique key uk_external_api_call_history_call_id (call_id),
    key idx_external_api_call_history_provider_id (provider, id),
    key idx_external_api_call_history_status_id (status, id),
    key idx_external_api_call_history_started_at (started_at)
);
