import Foundation

enum JapaneseAppStrings {
    private static let values: [String: String] = [
        "": "",
        "-": "-",
        ".": "。",
        "0-39": "0-39",
        "1 is easiest, 10 is expert-level.": "1 が最も簡単で、10 は専門家レベルです。",
        "40-69": "40-69",
        "70-89": "70-89",
        "90-100": "90-100",
        "A learning record that grows with you": "あなたとともに成長する学習記録",
        "A little more practice": "もう少し練習してください",
        "A new study question is ready. Tap to continue.": "新しい学習問題が準備されました。タップして続行します。",
        "A parent topic combines measurable subtopics in its tree. Each topic is capped at 5 answers so one high-volume topic cannot dominate.": "親トピックは、ツリー内の測定可能なサブトピックを結合します。各トピックの回答数は 5 つに制限されているため、1 つの大量のトピックが独占することはできません。",
        "A question is waiting for your answer.": "質問があなたの答えを待っています。",
        "A score graph appears after you grade answers.": "解答を採点すると、スコア グラフが表示されます。",
        "A study space built your way": "自分好みに組み立てられる学習スペース",
        "Ability": "能力",
        "Ability is placed on a 1–10 scale": "能力は 1 ～ 10 のスケールで表されます",
        "Ability position · 1–10": "アビリティポジション・1～10",
        "About BuddyStudy": "バディスタディについて",
        "Account deleted.": "アカウントが削除されました。",
        "Account Settings": "アカウント設定",
        "Activate": "活性化",
        "Activate topics": "トピックをアクティブにする",
        "Active Study": "アクティブな学習",
        "Active Topics": "アクティブなトピック",
        "Activities": "活動内容",
        "Activity": "活動",
        "Add": "追加",
        "Add at least one study.": "少なくとも 1 つのスタディを追加します。",
        "Add Billing": "請求の追加",
        "Add manually": "手動で追加",
        "Add Study": "学習を追加",
        "Add subtopic": "サブトピックの追加",
        "Agree All and Start": "すべてに同意して開始",
        "Agree and Start": "同意して開始",
        "Agree to all to receive event and new feature updates too. Marketing consent is optional.": "イベントや新機能のアップデートも受け取ることに全員が同意します。マーケティングの同意は任意です。",
        "All": "全て",
        "All studies": "すべての学習",
        "All Studies": "すべての学習",
        "Allowed": "許可された",
        "An API key error was detected.": "APIキーのエラーが検出されました。",
        "Analyzing answer evidence.": "回答の証拠を分析しています。",
        "and": "そして",
        "Answer": "回答",
        "Answer received.": "回答を受け取りました。",
        "Answer the current study room question before creating a new one.": "新しい質問を作成する前に、現在の自習室の質問に答えてください。",
        "answers": "答え",
        "API key": "APIキー",
        "API key is empty. Enter an OpenAI API key in Settings > Secrets.": "API キーが空です。 [設定] > [シークレット] に OpenAI API キーを入力します。",
        "API key is invalid. Check your OpenAI API key in Settings > Secrets.": "APIキーが無効です。 [設定] > [シークレット] で OpenAI API キーを確認します。",
        "API Status": "APIステータス",
        "API Traffic Logs": "APIトラフィックログ",
        "App events and errors appear here.": "アプリのイベントとエラーがここに表示されます。",
        "App preferences": "アプリの設定",
        "Architecture practice · Level 6": "建築演習 · レベル 6",
        "Automatically check for updates": "アップデートを自動的にチェックする",
        "Automatically download updates when available": "アップデートが利用可能な場合は自動的にダウンロードする",
        "Avatar": "アバター",
        "Average": "平均",
        "Avg": "平均",
        "Best": "最高",
        "Best streak that year": "その年の最高の記録",
        "Better AI output still depends on what you know. BuddyStudy keeps that knowledge active with short questions.": "AI の出力を向上させるには、やはり知識が必要です。 BuddyStudy は短い質問で知識を有効に保ちます。",
        "Bio": "バイオ",
        "Blue": "青",
        "Browse Question": "質問を見る",
        "BuddyStudy checks GitHub Releases and offers updates when a new DMG is available.": "BuddyStudy は GitHub リリースをチェックし、新しい DMG が利用可能になった場合には更新を提供します。",
        "BuddyStudy converts each answer's level and score into an ability estimate, then combines sample count and disagreement between answers. Mixed results across distant levels make the range wider. Answer more questions around that range to narrow it.": "BuddyStudy は、各回答のレベルとスコアを能力推定値に変換し、サンプル数と回答間の不一致を組み合わせます。離れたレベルにまたがる結果が混在すると、範囲が広がります。範囲を狭めるには、その範囲に関する質問にさらに答えてください。",
        "BuddyStudy did not save a repeated question.": "BuddyStudy は繰り返しの質問を保存しませんでした。",
        "BuddyStudy is running": "BuddyStudy が実行中です",
        "BuddyStudy is stopped": "BuddyStudy は停止しています",
        "Bug": "バグ",
        "By signing in, you agree to": "サインインすると、次のことに同意したことになります",
        "Cancel": "キャンセル",
        "Category": "カテゴリ",
        "Changing Language also sets the study language to match.": "言語を変更すると、学習言語もそれに合わせて設定されます。",
        "Check BuddyStudy notification and sound permissions directly in system settings.": "システム設定で BuddyStudy の通知とサウンドの許可を直接確認してください。",
        "Check for Updates...": "アップデートを確認してください...",
        "Check iCloud permission or the app's CloudKit setup.": "iCloud権限またはアプリのCloudKit設定を確認してください。",
        "Check the API key.": "APIキーを確認してください。",
        "Check the iCloud account or CloudKit permission.": "iCloudアカウントまたはCloudKitの権限を確認してください。",
        "Check usage, costs, and billing directly in OpenAI Platform.": "OpenAI Platform で使用量、コスト、請求を直接確認します。",
        "Check your internet connection and try again.": "インターネット接続を確認して、もう一度試してください。",
        "Checking": "チェック中",
        "Checking API key.": "APIキーを確認しています。",
        "Checking clipboard for API key.": "クリップボードの API キーをチェックしています。",
        "Child topics": "子トピック",
        "Choose whether question notifications play a sound.": "質問通知でサウンドを再生するかどうかを選択します。",
        "Clear": "クリア",
        "Clear All": "すべてクリア",
        "Clear Search": "検索をクリア",
        "Close": "閉じる",
        "Cloudflare Tunnel": "クラウドフレアトンネル",
        "Collapse topics": "トピックを折りたたむ",
        "Comment": "コメント",
        "Comments": "コメント",
        "Community Questions": "コミュニティの質問",
        "Community questions are currently unavailable.": "コミュニティの質問は現在利用できません。",
        "Community questions are disabled.": "コミュニティの質問は無効になっています。",
        "Community questions are enabled.": "コミュニティの質問が有効になります。",
        "Completion": "完了",
        "Completion is based on generated questions": "生成された質問に基づいて完了します",
        "Completion is the share of questions generated in the selected period that were answered and graded. No value is shown until a question has been generated.": "完了率は、選択した期間内に生成され、回答され採点された質問の割合です。質問が生成されるまで値は表示されません。",
        "Consent status affects feature availability and notification delivery. Open each detail link for the full text.": "同意ステータスは、機能の利用可能性と通知の配信に影響します。全文は各詳細リンクを開いてください。",
        "Continue another pending question or create a new one.": "別の保留中の質問を続行するか、新しい質問を作成します。",
        "Continue My Records": "私の記録を続ける",
        "Continue Oldest": "最も古いものを続行",
        "Continue on any device and keep your full learning history.": "どのデバイスでも継続して、完全な学習履歴を保存できます。",
        "Continue with required terms only": "必要な条件のみを続行してください",
        "Correct": "正しい",
        "Could not add the subtopic.": "サブトピックを追加できませんでした。",
        "Could not load community questions.": "コミュニティの質問を読み込めませんでした。",
        "Could not load your profile.": "プロフィールを読み込めませんでした。",
        "Could not send a notification. Check system notification settings.": "通知を送信できませんでした。システムの通知設定を確認してください。",
        "Count": "カウント",
        "Create a key here": "ここでキーを作成します",
        "Create your first study topic": "最初の学習トピックを作成する",
        "Creating a question for this topic and difficulty.": "このトピックと難易度に関する問題を作成します。",
        "Current": "現在",
        "Current Study": "現在の学習",
        "Custom": "カスタム",
        "Custom Color": "カスタムカラー",
        "Data sync": "データ同期",
        "Debug API URL": "デバッグ API URL",
        "Debugging Mode": "デバッグモード",
        "Delete": "削除",
        "Delete Account": "アカウントを削除",
        "Delete All Records": "すべてのレコードを削除",
        "Delete all saved app logs and API request and response logs.": "保存されているすべてのアプリ ログと API リクエストおよびレスポンス ログを削除します。",
        "Delete all saved questions, answers, and grading results.": "保存されている質問、回答、採点結果をすべて削除します。",
        "Delete Logs": "ログの削除",
        "Delete Record": "レコードの削除",
        "Delete selected topics?": "選択したトピックを削除しますか?",
        "Delete Study": "学習を削除",
        "Delete topics": "トピックの削除",
        "Describe what we can improve.": "改善できる点について説明します。",
        "Details": "詳細",
        "Developer Options": "開発者向けオプション",
        "Difficulty": "難易度",
        "Done": "完了",
        "Double-tap to focus the map on this study.": "ダブルタップすると、マップの焦点がこの調査に集中します。",
        "Draft auto-saved": "下書きの自動保存",
        "Duration": "間隔",
        "Each node uses its own topic records": "各ノードには、そのトピック自体の記録のみが表示されます。",
        "Each study keeps its own topic, difficulty, and prompt. Question interval is shared in Settings.": "各研究は独自のテーマ、難易度、およびプロンプトを維持します。質問間隔は設定で共有されます。",
        "Edit": "編集",
        "Edit Studies": "スタディの編集",
        "Edit Study": "学習を編集",
        "Email": "電子メール",
        "End": "終わり",
        "Enter an API key.": "API キーを入力します。",
        "Enter an http or https URL.": "http または https URL を入力します。",
        "Expand topics": "トピックを展開する",
        "Expand when you need individual study statistics.": "個別の研究統計が必要な場合に展開します。",
        "Explain how Kafka partitions relate to consumer groups.": "Kafka パーティションがコンシューマ グループにどのように関係するかを説明します。",
        "Explain how you would divide service boundaries and data ownership.": "サービスの境界とデータの所有権をどのように分割するかを説明します。",
        "Explanation": "説明",
        "Feature request": "機能リクエスト",
        "Feedback": "フィードバック",
        "Feedback sent.": "フィードバックが送信されました。",
        "Finish setup later in Settings.": "後で [設定] でセットアップを完了します。",
        "First": "初め",
        "Follow accuracy and difficulty changes for each topic.": "各トピックの精度と難易度の変化を追跡します。",
        "General": "一般",
        "Google Login becomes available after OAuth client configuration.": "Google ログインは、OAuth クライアントの設定後に利用可能になります。",
        "Grade Answer": "回答を採点",
        "Grade at least 6 answers in a topic to compare previous and recent progress.": "トピック内の少なくとも 6 つの回答を採点して、以前と最近の進捗状況を比較します。",
        "Grade more answers to build insights.": "さらに多くの回答を採点して洞察を構築します。",
        "Grading completed.": "採点が完了しました。",
        "Grading could not be completed. Please try again.": "採点を完了できませんでした。もう一度試してください。",
        "Green": "緑",
        "Growth": "成長",
        "Growth by study": "学習別の成長",
        "Growth by topic": "トピック別の成長",
        "Growth details": "成長の詳細",
        "Help improve BuddyStudy": "BuddyStudy の改善にご協力ください",
        "Hide": "隠れる",
        "Hide Hint": "ヒントを隠す",
        "Hint": "ヒント",
        "Holding steady": "安定して保持",
        "Home": "ホーム",
        "How growth is calculated": "成長率の計算方法",
        "How Range Works": "範囲の仕組み",
        "iCloud data is up to date.": "iCloudデータは最新です。",
        "iCloud is rate limiting requests. Try again shortly.": "iCloud はリクエストをレート制限しています。しばらくしてからもう一度お試しください。",
        "iCloud is temporarily unavailable. Try again later.": "iCloud が一時的に利用できなくなりました。後でもう一度試してください。",
        "iCloud sign-in is required. Check your iCloud account in System Settings.": "iCloudへのサインインが必要です。システム設定で iCloud アカウントを確認してください。",
        "iCloud storage is full, so sync could not finish. Free up iCloud storage and try again.": "iCloud ストレージがいっぱいのため、同期を完了できませんでした。 iCloud ストレージを解放して、もう一度試してください。",
        "iCloud Sync": "iCloud同期",
        "iCloud sync complete.": "iCloud同期が完了しました。",
        "iCloud sync failed because the network is unavailable. Reconnect and try again.": "ネットワークが利用できないため、iCloud 同期に失敗しました。再接続してもう一度お試しください。",
        "Identify a bottleneck in a scalable system.": "スケーラブルなシステムのボトルネックを特定します。",
        "If you don't have an OpenAI key": "OpenAI キーをお持ちでない場合",
        "If you see this, BuddyStudy notification permission is working.": "これが表示されている場合は、BuddyStudy の通知許可が機能しています。",
        "Ignore": "無視する",
        "Improving steadily": "着実に改善中",
        "Inappropriate question": "不適切な質問",
        "Includes children": "子供も含む",
        "Informational notifications": "情報通知",
        "Interval": "間隔",
        "Invalid API key": "無効な API キー",
        "Judging against the rubric.": "ルーブリックに照らして判断します。",
        "Keep it going today": "今日も続けてください",
        "Keep your learning progress with you": "学習の進捗状況を常に把握しておく",
        "Keep your records safe with an account": "アカウントで記録を安全に保管",
        "Keys are stored in app settings.": "キーはアプリの設定に保存されます。",
        "Language": "言語",
        "Last 30 Days": "過去 30 日間",
        "Last 7 Days": "過去 7 日間",
        "Last 90 Days": "過去90日間",
        "Last year": "去年",
        "Latest": "最新",
        "Learning activity": "学習活動",
        "Learning map": "学習マップ",
        "Learning rhythm": "学習リズム",
        "Level": "レベル",
        "Loaded iCloud data and merged this device's records.": "iCloud データをロードし、このデバイスのレコードを統合しました。",
        "Loaded the latest iCloud data.": "最新のiCloudデータをロードしました。",
        "Loading": "読み込み中",
        "Logs": "ログ",
        "Low": "低い",
        "Make Question Private": "質問を非公開にする",
        "Make Question Public": "質問を公開する",
        "Manage in Home": "自宅で管理",
        "Manage marketing updates such as events and feature announcements.": "イベントや機能の発表などのマーケティング更新を管理します。",
        "Manage your signed-in account and account deletion.": "サインインしているアカウントとアカウントの削除を管理します。",
        "Mark All as Read": "すべて既読としてマーク",
        "Marketing communications": "マーケティングコミュニケーション",
        "Marketing notifications": "マーケティング通知",
        "Max records": "最大レコード数",
        "Measured": "測定済み",
        "Measuring": "測定中",
        "Message": "メッセージ",
        "Messaging systems · Level 7": "メッセージング システム · レベル 7",
        "Model": "モデル",
        "Monthly questions": "毎月の質問",
        "More": "もっと",
        "Move the app to Trash and delete local settings and caches.": "アプリをゴミ箱に移動し、ローカル設定とキャッシュを削除します。",
        "My Studies": "マイ学習",
        "My Study": "マイ学習",
        "My Study Detail": "マイ学習の詳細",
        "Name": "名前",
        "Nearly Correct": "ほぼ正しい",
        "Needs Work": "仕事が必要です",
        "New email accounts require a verification code within 180 seconds.": "新しい電子メール アカウントには、180 秒以内に確認コードが必要です。",
        "New Question": "新しい質問",
        "Next Page": "次のページ",
        "Night marketing notifications": "ナイトマーケティングの通知",
        "No activity yet": "まだ活動はありません",
        "No API key error.": "APIキーエラーはありません。",
        "No comments yet.": "コメントはまだありません。",
        "No growth data yet": "成長データはまだありません",
        "No Logs": "ログなし",
        "No Matching Topics": "一致するトピックはありません",
        "No new suggestions were available. Retry or add one manually.": "新しい提案はありませんでした。再試行するか、手動で追加してください。",
        "No notifications yet": "まだ通知はありません",
        "No OpenAI key in clipboard.": "クリップボードに OpenAI キーがありません。",
        "No public questions to display.": "表示する公開質問はありません。",
        "No Question": "質問はありません",
        "No records": "記録がありません",
        "No Records": "記録がありません",
        "No Results": "結果はありません",
        "No Scores": "スコアなし",
        "No Scores in This Period": "このピリオドに得点はありません",
        "Not allowed": "許可されていません",
        "Notice": "知らせ",
        "Notification Settings": "通知設定",
        "Notification sound": "通知音",
        "Notifications": "通知",
        "Off": "オフ",
        "On": "の上",
        "Onboarding complete.": "オンボーディングが完了しました。",
        "Only the latest 1000 logs are kept. Older logs are deleted automatically.": "最新の 1000 件のログのみが保持されます。古いログは自動的に削除されます。",
        "Open Notification Settings": "通知設定を開く",
        "Open Questions": "未解決の質問",
        "Open selected study": "選択したスタディを開く",
        "Open study": "オープンスタディ",
        "Open Study...": "スタディを開く...",
        "OpenAI API key": "OpenAI APIキー",
        "OpenAI API key pasted.": "OpenAI API キーが貼り付けられました。",
        "OpenAI Connection": "OpenAI接続",
        "OpenAI model for question generation and grading.": "問題の生成と採点のための OpenAI モデル。",
        "OpenAI Usage / Billing": "OpenAIの使用/請求",
        "Opening the question from notification.": "通告から質問を開きます。",
        "Optional": "任意",
        "Other Answer": "その他の回答",
        "Overall": "全体",
        "Page Access": "ページアクセス",
        "Parent topics include subtopics": "親トピックにはサブトピックが含まれます",
        "Partially Correct": "部分的に正しい",
        "Password": "パスワード",
        "Paste": "ペースト",
        "Pause": "一時停止",
        "Pending": "保留中",
        "Pending Questions": "保留中の質問",
        "Period": "期間",
        "Photo Size": "写真のサイズ",
        "Preparing a new question": "新しい質問を準備しています",
        "Previous": "前の",
        "Previous Page": "前のページ",
        "Privacy Policy": "プライバシーポリシー",
        "Profile": "プロフィール",
        "Profile Character": "プロフィールキャラクター",
        "Profile Color": "プロファイルの色",
        "Profile Picture": "プロフィール写真",
        "Profile saved.": "プロフィールが保存されました。",
        "Prompt": "プロンプト",
        "Public Questions": "公開質問",
        "Question": "質問",
        "Question notifications": "質問通知",
        "Question Records": "質問履歴",
        "Question Visibility": "質問の可視性",
        "Questions disabled": "質問は無効になっています",
        "Questions enabled": "質問が有効になりました",
        "Quit BuddyStudy": "バディスタディをやめる",
        "Range": "範囲",
        "Ready to start BuddyStudy?": "BuddyStudy を始める準備はできましたか?",
        "Receive questions from this topic": "このトピックからの質問を受け付けます",
        "Recent": "最近の",
        "Recent Activity": "最近の活動",
        "Recent learning records": "最近の学習記録",
        "Recent record preview": "最近のレコードのプレビュー",
        "Recommended Prompt": "推奨されるプロンプト",
        "Record Detail": "履歴の詳細",
        "Record Settings": "履歴設定",
        "Records": "履歴",
        "Records appear after you create questions and grade answers.": "質問を作成し、回答を採点すると、レコードが表示されます。",
        "Red": "赤",
        "Refresh": "リフレッシュ",
        "Refresh suggestions": "提案を更新する",
        "Refreshed.": "リフレッシュしました。",
        "Reply": "返事",
        "Report": "報告",
        "Report submitted.": "レポートが提出されました。",
        "Request": "リクエスト",
        "Required": "必須",
        "Resend": "再送信",
        "Reset Debug Logs": "デバッグログをリセットする",
        "Reset tree layout": "ツリーレイアウトをリセット",
        "Resp": "応答",
        "Response": "応答",
        "Responses": "応答",
        "Resume": "再開する",
        "Retry": "リトライ",
        "Review": "レビュー",
        "Reviewing errors and omissions.": "誤りや欠落を確認します。",
        "Save": "保存",
        "Save settings, then create a new question.": "設定を保存して、新しい質問を作成します。",
        "Saved": "保存されました",
        "Saved this device's data to iCloud.": "このデバイスのデータを iCloud に保存しました。",
        "Saving": "保存",
        "Scheduled questions rotate through the topics you enable.": "スケジュールされた質問は、有効にしたトピックに応じて順番に表示されます。",
        "Score Distribution": "スコア分布",
        "Search": "検索",
        "Search records": "レコードの検索",
        "Search topic keywords and view public questions.": "トピックのキーワードを検索し、公開質問を表示します。",
        "Search Topics": "トピックの検索",
        "See My Progress": "私の進捗状況を確認する",
        "See topic progress and learning patterns at a glance.": "トピックの進行状況と学習パターンが一目でわかります。",
        "See your growth at a glance": "自分の成長が一目で分かる",
        "Select all": "すべて選択",
        "Selected Year": "選択した年",
        "Send": "送信",
        "Send Code": "コードを送信する",
        "Send feedback": "フィードバックを送信する",
        "Service boundaries · Level 7": "サービス境界 · レベル 7",
        "Set the difficulty and question style for each topic, then keep everything in one place.": "トピックごとに難易度と質問スタイルを設定し、すべてを 1 か所に保管します。",
        "Set Up BuddyStudy": "BuddyStudy のセットアップ",
        "Set Up Later": "後でセットアップする",
        "Settings": "設定",
        "Show": "見せる",
        "Show Hint": "ヒントを表示",
        "Show original": "オリジナルを表示",
        "Showing up to 20 questions at a time.": "一度に最大 20 個の質問を表示します。",
        "Sign In": "サインイン",
        "Sign in required.": "サインインが必要です。",
        "Sign in to keep study topics and question settings synced across devices.": "サインインして、学習トピックと質問設定をデバイス間で同期させます。",
        "Sign in to manage your studies.": "サインインして学習を管理します。",
        "Sign in to safely keep topic progress and learning statistics.": "サインインして、トピックの進行状況と学習統計を安全に保管します。",
        "Sign in to safely keep topic settings and progress with your account.": "サインインして、トピックの設定とアカウントの進行状況を安全に維持します。",
        "Sign in to search and view questions shared by other users. Your questions are private until you sign in.": "サインインして、他のユーザーが共有した質問を検索および表示します。質問はサインインするまで非公開です。",
        "Sign in to use records, statistics, and My Study sync.": "記録、統計、および My Study 同期を使用するには、サインインしてください。",
        "Sign in to write a comment.": "コメントを書くにはサインインしてください。",
        "Sign Out": "ログアウト",
        "Signed in as": "としてサインインしました",
        "Skip": "スキップ",
        "Skip the current ungraded question and move to the next pending one.": "現在の採点されていない質問をスキップして、次の保留中の質問に進みます。",
        "Some subtopics are still measuring": "一部のサブトピックはまだ測定中です",
        "Sort": "選別",
        "Start": "始める",
        "Start My Studies": "勉強を始めましょう",
        "Start today": "今日から始めましょう",
        "Statistics": "統計",
        "Stats": "統計",
        "Stats by Topic": "トピック別の統計",
        "Status": "状態",
        "Streak": "ストリーク",
        "Studies that may need review or more activity.": "見直しや追加の活動が必要な可能性のある研究。",
        "Studies to check first": "先に確認する学習",
        "Study": "学習",
        "Study days": "勉強日",
        "Study Overview": "学習状況",
        "Study question notifications depend on system permission and study settings.": "学習質問の通知は、システムの許可と学習設定によって異なります。",
        "Study Settings": "学習設定",
        "Study Setup": "学習の設定",
        "Study status tree": "学習ステータスツリー",
        "Study topic": "学習トピック",
        "Study Tree": "学習ツリー",
        "Suggested topics": "提案されたトピック",
        "Suggestions": "提案",
        "Summary of all subtopics in the selected period": "選択した期間のすべてのサブトピックの概要",
        "Support developer": "サポート開発者",
        "Sync conflicted with another device change. Sync again.": "同期が別のデバイスの変更と競合しました。再度同期します。",
        "Sync data exceeded an iCloud limit. Reduce older records and try again.": "同期データが iCloud の制限を超えました。古いレコードを減らして再試行してください。",
        "Sync is already in progress.": "同期はすでに進行中です。",
        "Sync Now": "今すぐ同期",
        "Sync Off": "同期オフ",
        "Sync On": "同期オン",
        "Syncing": "同期中",
        "Syncs study settings, the current question, answer drafts, records, and the OpenAI API key between iPhone and Mac.": "iPhone と Mac の間で学習設定、現在の質問、回答の下書き、記録、OpenAI API キーを同期します。",
        "System Design": "システム設計",
        "Tell us briefly what felt difficult or what you need.": "大変だと感じたことや必要なことを簡単に教えてください。",
        "Terms": "規約",
        "Terms and Consents": "規約と同意",
        "Terms of Service": "利用規約",
        "Test Notification": "テスト通知",
        "Test notification sent.": "テスト通知が送信されました。",
        "The API key is stored in this Mac's app settings. You can change it later in Settings > Secrets.": "API キーは、この Mac のアプリ設定に保存されます。後で [設定] > [シークレット] で変更できます。",
        "The app is free. You only need your own OpenAI API key.": "アプリは無料です。必要なのは独自の OpenAI API キーのみです。",
        "The app, local settings, and caches will be deleted, then BuddyStudy will quit.": "アプリ、ローカル設定、キャッシュが削除され、BuddyStudy が終了します。",
        "The latest 3–5 graded answers are compared with the preceding 3–5. Fewer than 6 answers in a topic is shown as Measuring.": "最新の 3 ～ 5 の採点された回答が、前の 3 ～ 5 の回答と比較されます。トピック内の回答が 6 件未満の場合は、「測定中」として表示されます。",
        "The more you study, the more of your questions and answers you can revisit.": "勉強すればするほど、より多くの質問と回答を再検討できます。",
        "The question could not be skipped. Please try again shortly.": "質問をスキップすることはできませんでした。しばらくしてからもう一度お試しください。",
        "The response data could not be read. Please try again shortly.": "応答データを読み取れませんでした。しばらくしてからもう一度お試しください。",
        "The response is taking longer than expected. Please try again shortly.": "応答に予想よりも時間がかかっています。しばらくしてからもう一度お試しください。",
        "The server response could not be read. Please try again shortly.": "サーバー応答を読み取れませんでした。しばらくしてからもう一度お試しください。",
        "The service is temporarily unavailable. Please try again shortly.": "サービスは一時的にご利用いただけません。しばらくしてからもう一度お試しください。",
        "The system topic tree supports five levels. Continue studying here or add a topic to an earlier level.": "システム トピック ツリーは 5 つのレベルをサポートします。ここで学習を続けるか、前のレベルにトピックを追加してください。",
        "The top-level topic combines all subtopics; each row shows an individual score.": "最上位のトピックはすべてのサブトピックを結合します。各行には個別のスコアが表示されます。",
        "This app build does not include iCloud entitlement. Reinstall the latest release.": "このアプリのビルドには iCloud 資格が含まれていません。最新リリースを再インストールします。",
        "This email is new. Send a verification code, then enter it to sign in.": "このメールは新しいものです。確認コードを送信し、それを入力してサインインします。",
        "This Month": "今月",
        "This page is available after sign-in.": "このページはサインイン後に利用できます。",
        "This question was already skipped or deleted and cannot be opened.": "この質問はすでにスキップまたは削除されているため、開くことができません。",
        "This topic already exists in the tree.": "このトピックはすでにツリーに存在します。",
        "This week": "今週",
        "Thread activity such as comments and likes will appear here.": "コメントやいいねなどのスレッドのアクティビティがここに表示されます。",
        "Timer paused because the API key is empty. Add it in Settings > Secrets.": "API キーが空のためタイマーが一時停止しました。 [設定] > [シークレット] に追加します。",
        "Tip Me": "教えてください",
        "Today": "今日",
        "Topic": "トピック",
        "Topic Browser": "トピックブラウザ",
        "Topic Level Trend": "トピックレベルの傾向",
        "Topic progress preview": "トピックの進行状況のプレビュー",
        "Topic Summary": "トピックの概要",
        "Topics": "トピックス",
        "Translated into English": "英語に翻訳",
        "Trend": "傾向",
        "Try a broader search or a wider period.": "より広範囲またはより広い期間で検索してみてください。",
        "Try again shortly or pull down to refresh.": "しばらくしてから再試行するか、プルダウンして更新してください。",
        "Try another search term.": "別の検索語を試してください。",
        "Turn on BuddyStudy notifications in iPhone Settings to receive notifications.": "通知を受け取るには、iPhone の設定で BuddyStudy 通知をオンにします。",
        "Two non-overlapping windows are compared": "重なり合わない 2 つのウィンドウが比較されます",
        "Unable to load notifications": "通知を読み込めません",
        "Unavailable Notification": "利用不可の通知",
        "Ungraded": "グレードなし",
        "Uninstall BuddyStudy": "BuddyStudy をアンインストールする",
        "Uninstall BuddyStudy?": "BuddyStudy をアンインストールしますか?",
        "Unmeasured": "未測定",
        "Unread": "未読",
        "Up one level": "一つ上のレベルへ",
        "Updates": "アップデート",
        "Updates are unavailable when BuddyStudy is running from a DMG or temporary location. Move BuddyStudy.app to Applications and relaunch it.": "BuddyStudy が DMG または一時的な場所から実行されている場合、アップデートは利用できません。 BuddyStudy.app をアプリケーションに移動し、再起動します。",
        "Usage": "使用法",
        "Use Photo": "写真を使用する",
        "Used for question generation and grading. Enter a normal project API key.": "問題の生成と採点に使用されます。通常のプロジェクト API キーを入力します。",
        "Uses the system topic catalog first and generates missing suggestions when needed.": "最初にシステム トピック カタログを使用し、必要に応じて不足している提案を生成します。",
        "Verification Code": "検証コード",
        "Verification code sent.": "確認コードが送信されました。",
        "Verifying the grading decision.": "採点の決定を確認します。",
        "Version": "バージョン",
        "View full tree": "ツリー全体を表示",
        "View translation": "翻訳を見る",
        "View Usage / Costs": "使用量/コストを表示する",
        "Visible only to signed-in users. When off, your generated questions are not shown in the community feed.": "サインインしているユーザーにのみ表示されます。オフにすると、生成された質問はコミュニティ フィードに表示されません。",
        "We add “(score − 50) ÷ 30” to the question difficulty, then clamp it to 1–10. For example, a score of 80 at difficulty 6 gives an ability position of 7.": "問題の難易度に「(スコア − 50) ÷ 30」を加えて、1 ～ 10 に固定します。たとえば、難易度 6 でスコア 80 の場合、能力位置は 7 になります。",
        "When debugging is on and the URL is valid, all API requests are sent here.": "デバッグがオンで URL が有効な場合、すべての API リクエストがここに送信されます。",
        "When enabled, Developer logs are available.": "有効にすると、開発者ログが利用可能になります。",
        "When enabled, only graded questions that you individually mark public are shown to other users.": "有効にすると、個別に公開マークを付けた採点済みの質問のみが他のユーザーに表示されます。",
        "Widen the period or grade a new answer to show stats.": "期間を広げるか、新しい回答を採点して統計を表示します。",
        "Write a comment": "コメントを書く",
        "Write answer": "答えを書く",
        "Year": "年",
        "You have reached this month's question limit.": "今月の質問制限に達しました。",
        "You have unsaved changes. Values are kept even if API key validation fails.": "未保存の変更があります。 API キーの検証が失敗した場合でも、値は保持されます。",
        "You will be signed out immediately and cannot use this account again. Your profile, public questions, studies, and related records are then deleted asynchronously.": "すぐにサインアウトされ、このアカウントを再度使用することはできません。その後、あなたのプロフィール、公開質問、研究、および関連記録が非同期的に削除されます。",
        "Your account and related records cannot be recovered after deletion.": "アカウントと関連記録は、削除後に復元することはできません。",
        "Your new question is ready.": "新しい質問の準備ができました。",
        "Your new question is ready. Your current draft was kept.": "新しい質問の準備ができました。現在の下書きは保存されました。",
        "Your personal record grows with every study session.": "勉強会を重ねるごとに個人記録が伸びていきます。",
    ]

    static func translation(for english: String) -> String {
        values[english] ?? english
    }

    static func hasTranslation(for english: String) -> Bool {
        values[english] != nil
    }
}
