apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kubernetes

patches:
  - path: patches/postgres-linux-hostpath.yaml
  - path: patches/redis-linux-hostpath-0.yaml
  - path: patches/redis-linux-hostpath-1.yaml
  - path: patches/redis-linux-hostpath-2.yaml
