package com.buddystudy.backend.study.adapter.outbound.persistence

import com.buddystudy.backend.auth.Principal
import com.buddystudy.backend.common.application.error.ApiErrorCode
import com.buddystudy.backend.common.application.error.ApiException
import com.buddystudy.backend.config.BuddyStudyProperties
import com.buddystudy.backend.localization.application.port.ContentLocalizationPort
import com.buddystudy.backend.study.application.port.inbound.CreateStudyTopicCommand
import com.buddystudy.backend.study.application.port.inbound.ExpectedStudyMetadata
import com.buddystudy.backend.study.application.port.inbound.UpdateStudyCommand
import com.buddystudy.backend.study.application.port.outbound.QuestionPort
import com.buddystudy.backend.study.application.port.outbound.QuestionStatsPort
import com.buddystudy.backend.study.application.service.StudySyncService
import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import kotlinx.coroutines.withTimeoutOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Timeout
import org.mockito.Mockito
import org.springframework.core.convert.converter.Converter
import org.springframework.dao.OptimisticLockingFailureException
import org.springframework.data.convert.ReadingConverter
import org.springframework.data.convert.WritingConverter
import org.springframework.data.r2dbc.convert.MappingR2dbcConverter
import org.springframework.data.r2dbc.convert.R2dbcCustomConversions
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate
import org.springframework.data.r2dbc.dialect.MySqlDialect
import org.springframework.data.relational.core.mapping.RelationalMappingContext
import org.springframework.r2dbc.connection.R2dbcTransactionManager
import org.springframework.r2dbc.core.DatabaseClient
import org.springframework.transaction.reactive.TransactionalOperator
import org.springframework.transaction.reactive.executeAndAwait
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.util.UUID

/**
 * In-memory SQL and transaction contracts, not execution of the MySQL Flyway DDL.
 * The small history tables mirror V3/V63/V97/V103 FK behavior only. No Docker,
 * account, quota, provider, or existing database is contacted by this fixture.
 */
@Timeout(15)
class StudyRepositoryMetadataPatchTest {
    private val now = Instant.parse("2026-09-01T01:00:00Z")
    private val connections = ConnectionFactories.get(
        "r2dbc:h2:mem:///study-metadata-${UUID.randomUUID()};MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000",
    )
    private val database = DatabaseClient.create(connections)
    private val transactions = TransactionalOperator.create(R2dbcTransactionManager(connections))
    private val repository: StudyRepository
    private val questions = Mockito.mock(QuestionPort::class.java)
    private val stats = Mockito.mock(QuestionStatsPort::class.java)
    private val localizations = Mockito.mock(ContentLocalizationPort::class.java)
    private val service: StudySyncService
    private val principal = Principal(7, "metadata-fixture", 70, anonymous = false)

    init {
        val conversions = R2dbcCustomConversions.of(MySqlDialect.INSTANCE, ReadUtcInstant, WriteUtcInstant)
        val mapping = RelationalMappingContext().also { it.setSimpleTypeHolder(conversions.simpleTypeHolder) }
        repository = StudyRepository(
            R2dbcEntityTemplate(database, MySqlDialect.INSTANCE, MappingR2dbcConverter(mapping, conversions)),
            BuddyStudyProperties(),
        )
        service = StudySyncService(repository, questions, stats, localizations)
    }

    @BeforeEach
    fun setUp(): Unit = runBlocking {
        execute("create table users (id bigint primary key)")
        execute("insert into users(id) values (7), (99)")
        execute(
            """
            create table studies (
                id bigint generated by default as identity primary key,
                device_id varchar(191) not null default 'metadata-fixture',
                user_id bigint not null,
                parent_study_id bigint,
                sort_order integer not null default 0,
                topic varchar(255) not null,
                difficulty_level integer not null default 5,
                interval_minutes integer not null default 15,
                enabled boolean not null default false,
                active_for_questions boolean not null default true,
                notification_sound varchar(100),
                custom_prompt text not null default '',
                openai_model varchar(100) not null default 'fixture-model',
                max_history_count integer not null default 100,
                next_due_at timestamp(6),
                schedule_claimed_until timestamp(6),
                last_sent_at timestamp(6),
                last_error text,
                created_at timestamp(6) not null default current_timestamp,
                updated_at timestamp(6) not null default current_timestamp,
                version bigint not null default 0,
                foreign key (user_id) references users(id),
                foreign key (parent_study_id) references studies(id) on delete cascade
            )
            """.trimIndent(),
        )
        execute("create index idx_studies_user_parent_order on studies(user_id, parent_study_id, sort_order, id)")
        execute("create index idx_studies_parent on studies(parent_study_id)")
        execute(
            "create table questions (id bigint primary key, study_id bigint, answer text, score int, foreign key (study_id) references studies(id) on delete set null)",
        )
        execute(
            "create table voice_tutor_sessions (id varchar(36) primary key, study_id bigint, foreign key (study_id) references studies(id) on delete set null)",
        )
        execute(
            "create table voice_study_learning_records (id bigint primary key, session_id varchar(36) not null, study_id bigint not null, topic varchar(255), difficulty int, answer text, score int, foreign key (session_id) references voice_tutor_sessions(id) on delete cascade)",
        )
    }

    @Test
    fun `partial SQL preserves scheduling preferences tree identity and history while returning the current row`(): Unit = runBlocking {
        insertStudy(10, "Root")
        insertStudy(11, "Redis", parentId = 10)
        database.sql(
            """
            update studies set sort_order = 8, difficulty_level = 3, interval_minutes = 47,
                enabled = true, active_for_questions = false, notification_sound = 'bell.caf',
                custom_prompt = 'Keep this preference', openai_model = 'chosen-model', max_history_count = 231,
                next_due_at = :due, schedule_claimed_until = :claim, last_sent_at = :sent, last_error = 'Existing error'
            where id = 11
            """.trimIndent(),
        ).bind("due", now.utc()).bind("claim", now.plusSeconds(35).utc()).bind("sent", now.minusSeconds(600).utc())
            .fetch().rowsUpdated().awaitSingle()
        val before = requireNotNull(repository.findByIdAndUserId(11, 7))
        val renamed = transaction { service.updateStudy(principal, 11, UpdateStudyCommand(topic = " Redis Streams ")) }
        assertThat(renamed.topic).isEqualTo("Redis Streams")
        assertThat(renamed.difficultyLevel).isEqualTo(3)
        val changed = transaction { service.updateStudy(principal, 11, UpdateStudyCommand(difficultyLevel = 7)) }
        val after = requireNotNull(repository.findByIdAndUserId(11, 7))

        assertThat(changed.id).isEqualTo(11)
        assertThat(changed.parentStudyId).isEqualTo(10)
        assertThat(changed.nextDueAt).isEqualTo(now)
        assertThat(after).usingRecursiveComparison()
            .ignoringFields("topic", "difficultyLevel", "updatedAt", "version")
            .isEqualTo(before)
        assertThat(after.topic).isEqualTo("Redis Streams")
        assertThat(after.difficultyLevel).isEqualTo(7)
        Mockito.verifyNoInteractions(questions, stats, localizations)
    }

    @Test
    fun `missing and foreign updates return null while an identical repeated patch still reselects the owned row`(): Unit = runBlocking {
        insertStudy(11, "Redis")
        insertStudy(99, "Private", userId = 99)

        assertThat(transaction { listOf(repository.updateTopicMetadata(11, 7, "Redis", null, now)) }.single()).isNotNull()
        assertThat(transaction { listOf(repository.updateTopicMetadata(11, 7, "Redis", null, now)) }.single()).isNotNull()
        assertThat(transaction { listOf(repository.updateTopicMetadata(99, 7, "Wrong owner", 1, now)) }.single()).isNull()
        assertThat(transaction { listOf(repository.updateTopicMetadata(999, 7, "Missing", 1, now)) }.single()).isNull()
        assertThat(repository.findByIdAndUserId(99, 99)?.topic).isEqualTo("Private")
        assertThat(repository.findByIdAndUserId(11, 7)?.updatedAt).isEqualTo(now)
        assertThat(transaction { repository.lockMutationOwner(123456) }).isFalse()
    }

    @Test
    fun `a migrated existing row at version zero is updated instead of inserted`(): Unit = runBlocking {
        insertStudy(11, "Redis")
        val existing = requireNotNull(repository.findByIdAndUserId(11, 7))
        assertThat(existing.version).isZero()
        existing.intervalMinutes = 45

        val saved = transaction { repository.save(existing) }

        assertThat(saved.id).isEqualTo(11)
        assertThat(saved.version).isEqualTo(1)
        assertThat(repository.findByIdAndUserId(11, 7)?.intervalMinutes).isEqualTo(45)
        val rowCount = database.sql("select count(*) from studies where id = 11")
            .map { row, _ -> row.get(0, java.lang.Long::class.java)!!.toLong() }
            .one().awaitSingle()
        assertThat(rowCount).isEqualTo(1)
    }

    @Test
    fun `concurrent disjoint patches wait on the owner fence and retain both changes`(): Unit = runBlocking {
        insertStudy(11, "Redis")
        val firstPatched = CompletableDeferred<Unit>()
        val releaseFirst = CompletableDeferred<Unit>()
        val secondEntered = CompletableDeferred<Unit>()
        val first = async(Dispatchers.IO) {
            transaction {
                service.updateStudy(principal, 11, UpdateStudyCommand(topic = "Streams"))
                firstPatched.complete(Unit)
                releaseFirst.await()
            }
        }
        try {
            withTimeout(5_000) { firstPatched.await() }
            val second = async(Dispatchers.IO) {
                transaction {
                    secondEntered.complete(Unit)
                    service.updateStudy(principal, 11, UpdateStudyCommand(difficultyLevel = 8))
                }
            }
            withTimeout(5_000) { secondEntered.await() }
            assertThat(withTimeoutOrNull(100) { second.await() }).isNull()
            releaseFirst.complete(Unit)
            withTimeout(5_000) { first.await() }
            assertThat(withTimeout(5_000) { second.await() }.topic).isEqualTo("Streams")
        } finally {
            releaseFirst.complete(Unit)
        }
        assertThat(repository.findByIdAndUserId(11, 7)?.topic).isEqualTo("Streams")
        assertThat(repository.findByIdAndUserId(11, 7)?.difficultyLevel).isEqualTo(8)
    }

    @Test
    fun `voice patch waits for a concurrent app update then rejects its stale frozen identity`(): Unit = runBlocking {
        insertStudy(11, "Redis")
        val appPatched = CompletableDeferred<Unit>()
        val releaseApp = CompletableDeferred<Unit>()
        val voiceEntered = CompletableDeferred<Unit>()
        val app = async(Dispatchers.IO) {
            transaction {
                service.updateStudy(principal, 11, UpdateStudyCommand(topic = "Redis Streams"))
                appPatched.complete(Unit)
                releaseApp.await()
            }
        }
        try {
            withTimeout(5_000) { appPatched.await() }
            val voice = async(Dispatchers.IO) {
                runCatching {
                    transaction {
                        voiceEntered.complete(Unit)
                        service.updateStudy(
                            principal,
                            11,
                            UpdateStudyCommand(
                                topic = "Voice rename",
                                expectedCurrent = ExpectedStudyMetadata(null, "Redis", 5),
                            ),
                        )
                    }
                }
            }
            withTimeout(5_000) { voiceEntered.await() }
            assertThat(withTimeoutOrNull(100) { voice.await() }).isNull()
            releaseApp.complete(Unit)
            withTimeout(5_000) { app.await() }
            val conflict = withTimeout(5_000) { voice.await() }.exceptionOrNull() as ApiException
            assertThat(conflict.status.value()).isEqualTo(409)
            assertThat(conflict.code).isEqualTo(ApiErrorCode.STUDY_TREE_CHANGED)
        } finally {
            releaseApp.complete(Unit)
        }
        assertThat(repository.findByIdAndUserId(11, 7)?.topic).isEqualTo("Redis Streams")
    }

    @Test
    fun `stale full row save cannot undo a committed voice metadata patch`(): Unit = runBlocking {
        insertStudy(11, "Redis")
        val staleSettingsRow = requireNotNull(repository.findByIdAndUserId(11, 7))

        transaction {
            service.updateStudy(
                principal,
                11,
                UpdateStudyCommand(
                    topic = "Redis Streams",
                    expectedCurrent = ExpectedStudyMetadata(null, "Redis", 5),
                ),
            )
        }
        staleSettingsRow.intervalMinutes = 90
        val failure = runCatching {
            transaction { repository.save(staleSettingsRow) }
        }.exceptionOrNull()

        assertThat(failure).isInstanceOf(OptimisticLockingFailureException::class.java)
        val current = requireNotNull(repository.findByIdAndUserId(11, 7))
        assertThat(current.topic).isEqualTo("Redis Streams")
        assertThat(current.intervalMinutes).isEqualTo(15)
    }

    @Test
    fun `a concurrent child create rechecks normalized uniqueness after a rename commits`(): Unit = runBlocking {
        insertStudy(10, "Parent")
        insertStudy(11, "Other root")
        val firstPatched = CompletableDeferred<Unit>()
        val releaseFirst = CompletableDeferred<Unit>()
        val secondEntered = CompletableDeferred<Unit>()
        val first = async(Dispatchers.IO) {
            transaction {
                service.updateStudy(principal, 11, UpdateStudyCommand(topic = "Redis Streams"))
                firstPatched.complete(Unit)
                releaseFirst.await()
            }
        }
        try {
            withTimeout(5_000) { firstPatched.await() }
            val second = async(Dispatchers.IO) {
                runCatching {
                    transaction {
                        secondEntered.complete(Unit)
                        service.createStudyTopic(principal, 10, CreateStudyTopicCommand(topic = "  REDIS   STREAMS "))
                    }
                }
            }
            withTimeout(5_000) { secondEntered.await() }
            assertThat(withTimeoutOrNull(100) { second.await() }).isNull()
            releaseFirst.complete(Unit)
            withTimeout(5_000) { first.await() }
            val conflict = withTimeout(5_000) { second.await() }.exceptionOrNull() as ApiException
            assertThat(conflict.status.value()).isEqualTo(409)
        } finally {
            releaseFirst.complete(Unit)
        }
        assertThat(repository.findAllByUserId(7).map { it.topic }).containsExactly("Parent", "Redis Streams")
        Mockito.verifyNoInteractions(questions, stats, localizations)
    }

    @Test
    fun `guarded delete rejects changed scope then cascades only nodes while retaining question and voice history`(): Unit = runBlocking {
        insertStudy(10, "Root")
        insertStudy(11, "Redis", parentId = 10)
        execute("insert into questions(id, study_id, answer, score) values (81, 11, 'Original typed answer', 85)")
        execute("insert into voice_tutor_sessions(id, study_id) values ('synthetic-prior-session', 11)")
        execute("insert into voice_study_learning_records(id, session_id, study_id, topic, difficulty, answer, score) values (91, 'synthetic-prior-session', 11, 'Redis', 3, 'Original spoken answer', 85)")

        val changed = runCatching { transaction { service.deleteStudy(principal, 10, listOf(10L)) } }.exceptionOrNull() as ApiException
        assertThat(changed.code).isEqualTo(ApiErrorCode.STUDY_TREE_CHANGED)
        assertThat(repository.findAllByUserId(7)).hasSize(2)
        transaction { service.deleteStudy(principal, 10, listOf(11L, 10L)) }

        assertThat(repository.findAllByUserId(7)).isEmpty()
        val question = database.sql("select study_id, answer, score from questions where id = 81").fetch().one().awaitSingle()
        assertThat(question["study_id"]).isNull()
        assertThat(question["answer"]).isEqualTo("Original typed answer")
        assertThat((question["score"] as Number).toInt()).isEqualTo(85)
        val session = database.sql("select study_id from voice_tutor_sessions where id = 'synthetic-prior-session'").fetch().one().awaitSingle()
        assertThat(session["study_id"]).isNull()
        val voice = database.sql("select study_id, topic, difficulty, answer, score from voice_study_learning_records where id = 91").fetch().one().awaitSingle()
        assertThat((voice["study_id"] as Number).toLong()).isEqualTo(11)
        assertThat(voice["topic"]).isEqualTo("Redis")
        assertThat((voice["difficulty"] as Number).toInt()).isEqualTo(3)
        assertThat(voice["answer"]).isEqualTo("Original spoken answer")
        assertThat((voice["score"] as Number).toInt()).isEqualTo(85)
        Mockito.verifyNoInteractions(questions, stats, localizations)
    }

    @Test
    fun `subtree traversal rejects mixed ownership and cycles and returns one bounded overflow ID`(): Unit = runBlocking {
        insertStudy(10, "Root")
        insertStudy(11, "Child", parentId = 10, userId = 99)
        assertThat(transaction {
            repository.lockMutationOwner(7)
            listOf(repository.findSubtreeIdsForMutation(7, 10, 129))
        }.single()).isNull()
        execute("update studies set user_id = 7 where id = 11")
        execute("update studies set parent_study_id = 11 where id = 10")
        assertThat(transaction {
            repository.lockMutationOwner(7)
            listOf(repository.findSubtreeIdsForMutation(7, 10, 129))
        }.single()).isNull()
        execute("update studies set parent_study_id = null where id = 10")
        insertStudy(1000, "Large root")
        for (id in 1001L..1130L) insertStudy(id, "Child $id", parentId = 1000)
        val bounded = transaction {
            repository.lockMutationOwner(7)
            requireNotNull(repository.findSubtreeIdsForMutation(7, 1000, 129))
        }
        assertThat(bounded).hasSize(129)
        assertThat(bounded.first()).isEqualTo(1000)
        assertThat(bounded).doesNotHaveDuplicates()
    }

    @Test
    fun `a child created under the common owner lock makes an earlier delete confirmation stale`(): Unit = runBlocking {
        insertStudy(10, "Root")
        val childInserted = CompletableDeferred<Unit>()
        val releaseFirst = CompletableDeferred<Unit>()
        val secondEntered = CompletableDeferred<Unit>()
        val first = async(Dispatchers.IO) {
            transaction {
                val child = service.createStudyTopic(principal, 10, CreateStudyTopicCommand(topic = "New child"))
                childInserted.complete(Unit)
                releaseFirst.await()
                child
            }
        }
        try {
            withTimeout(5_000) { childInserted.await() }
            val second = async(Dispatchers.IO) {
                runCatching {
                    transaction {
                        secondEntered.complete(Unit)
                        service.deleteStudy(principal, 10, listOf(10L))
                    }
                }
            }
            withTimeout(5_000) { secondEntered.await() }
            assertThat(withTimeoutOrNull(100) { second.await() }).isNull()
            releaseFirst.complete(Unit)
            withTimeout(5_000) { first.await() }
            val stale = withTimeout(5_000) { second.await() }.exceptionOrNull() as ApiException
            assertThat(stale.code).isEqualTo(ApiErrorCode.STUDY_TREE_CHANGED)
        } finally {
            releaseFirst.complete(Unit)
        }
        assertThat(repository.findAllByUserId(7)).hasSize(2)
        assertThat(repository.findAllByUserId(7).map { it.topic }).containsExactlyInAnyOrder("Root", "New child")
    }

    private suspend fun <T : Any> transaction(block: suspend () -> T): T =
        requireNotNull(transactions.executeAndAwait { block() })

    private suspend fun execute(sql: String): Unit {
        database.sql(sql).fetch().rowsUpdated().awaitSingle()
    }

    private suspend fun insertStudy(id: Long, topic: String, parentId: Long? = null, userId: Long = 7): Unit {
        var insert = database.sql(
            "insert into studies(id, user_id, parent_study_id, topic, created_at, updated_at) values (:id, :userId, :parentId, :topic, :created, :updated)",
        ).bind("id", id).bind("userId", userId).bind("topic", topic).bind("created", now.utc()).bind("updated", now.utc())
        insert = parentId?.let { insert.bind("parentId", it) } ?: insert.bindNull("parentId", java.lang.Long::class.java)
        insert.fetch().rowsUpdated().awaitSingle()
    }

    private fun Instant.utc(): LocalDateTime = LocalDateTime.ofInstant(this, ZoneOffset.UTC)

    @ReadingConverter
    private object ReadUtcInstant : Converter<LocalDateTime, Instant> {
        override fun convert(source: LocalDateTime): Instant = source.toInstant(ZoneOffset.UTC)
    }

    @WritingConverter
    private object WriteUtcInstant : Converter<Instant, LocalDateTime> {
        override fun convert(source: Instant): LocalDateTime = LocalDateTime.ofInstant(source, ZoneOffset.UTC)
    }
}
