package com.buddystudy.backend.scheduler.adapter.outbound.persistence

import com.buddystudy.backend.scheduler.application.model.JobRunStatus
import com.buddystudy.backend.scheduler.application.model.JobTriggerType
import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.DatabaseClient

class ScheduledJobRunPersistenceAdapterTest {
    private val client = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///scheduler;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1"),
    )
    private val adapter = ScheduledJobRunPersistenceAdapter(client)

    @BeforeEach
    fun setUpSchema(): Unit = runBlocking {
        execute(
            """
            create table if not exists scheduled_jobs (
                job_name varchar(120) primary key, enabled boolean not null default true,
                schedule_type varchar(40) not null, schedule_value varchar(120) not null,
                timeout_seconds integer not null default 300
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists scheduled_job_runs (
                id bigint generated by default as identity primary key, job_name varchar(120) not null,
                trigger_type varchar(40) not null, status varchar(40) not null,
                started_at timestamp with time zone not null, finished_at timestamp with time zone null,
                duration_ms bigint null, summary varchar(500) null, error_message varchar(1000) null,
                retry_of_run_id bigint null, created_by varchar(120) not null
            )
            """.trimIndent(),
        )
        execute("delete from scheduled_job_runs")
        execute("delete from scheduled_jobs")
    }

    @Test
    fun `stores job run lifecycle without blocking jdbc`(): Unit = runBlocking {
        val started = adapter.start("event-outbox-dispatch", JobTriggerType.SCHEDULED, null, "system")

        val finished = adapter.finish(started.id, JobRunStatus.SUCCESS, "rows=9", null, 17)
        val page = adapter.findRuns("event-outbox-dispatch", null, 10, 0)

        assertThat(finished.status).isEqualTo(JobRunStatus.SUCCESS)
        assertThat(finished.summary).isEqualTo("rows=9")
        assertThat(page.runs).containsExactly(finished)
        assertThat(page.totalCount).isEqualTo(1)
    }

    @Test
    fun `expands multiple scheduler names into r2dbc bind markers`(): Unit = runBlocking {
        execute(
            """
            insert into scheduled_jobs (job_name, enabled, schedule_type, schedule_value, timeout_seconds) values
                ('question-schedule', true, 'FIXED_DELAY', '30s', 90),
                ('user-stats-refresh', false, 'CRON', '0 */5 * * * *', 600)
            """.trimIndent(),
        )
        val run = adapter.finish(
            adapter.start("question-schedule", JobTriggerType.SCHEDULED, null, "system").id,
            JobRunStatus.SUCCESS,
            "ok",
            null,
            10,
        )

        val snapshots = adapter.findSnapshots(listOf("question-schedule", "user-stats-refresh"))

        assertThat(snapshots.map { it.jobName }).containsExactly("question-schedule", "user-stats-refresh")
        assertThat(snapshots.first().latestRun).isEqualTo(run)
        assertThat(snapshots.first().lastSuccessfulRun).isEqualTo(run)
        assertThat(snapshots.last().enabled).isFalse()
    }

    private suspend fun execute(sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }
}
