package com.buddystudy.backend.scheduler.adapter.outbound.persistence

import com.buddystudy.backend.scheduler.application.model.JobRunStatus
import com.buddystudy.backend.scheduler.application.model.JobTriggerType
import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.r2dbc.core.DatabaseClient
import java.time.Instant

class ScheduledJobRunPersistenceAdapterTest {
    private val client = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///scheduler;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1"),
    )
    private val adapter = ScheduledJobRunPersistenceAdapter(client)

    @BeforeEach
    fun setUpSchema(): Unit = runBlocking {
        execute(
            """
            create table if not exists scheduled_jobs (
                job_name varchar(120) primary key, enabled boolean not null default true,
                schedule_type varchar(40) not null, schedule_value varchar(120) not null,
                timeout_seconds integer not null default 300
            )
            """.trimIndent(),
        )
        execute(
            """
            create table if not exists scheduled_job_runs (
                id bigint generated by default as identity primary key, job_name varchar(120) not null,
                trigger_type varchar(40) not null, status varchar(40) not null,
                started_at timestamp with time zone not null, finished_at timestamp with time zone null,
                duration_ms bigint null, summary varchar(500) null, error_message varchar(1000) null,
                retry_of_run_id bigint null, created_by varchar(120) not null
            )
            """.trimIndent(),
        )
        execute(
            """
            create index if not exists idx_scheduled_job_runs_name_started_id
            on scheduled_job_runs (job_name, started_at desc, id desc)
            """.trimIndent(),
        )
        execute(
            """
            create index if not exists idx_scheduled_job_runs_name_status_started_id
            on scheduled_job_runs (job_name, status, started_at desc, id desc)
            """.trimIndent(),
        )
        execute(
            """
            create index if not exists idx_scheduled_job_runs_started_id
            on scheduled_job_runs (started_at desc, id desc)
            """.trimIndent(),
        )
        execute("delete from scheduled_job_runs")
        execute("delete from scheduled_jobs")
    }

    @Test
    fun `stores job run lifecycle without blocking jdbc`(): Unit = runBlocking {
        val started = adapter.start("event-outbox-dispatch", JobTriggerType.SCHEDULED, null, "system")

        val finished = adapter.finish(started.id, JobRunStatus.SUCCESS, "rows=9", null, 17)
        val page = adapter.findRuns("event-outbox-dispatch", null, 10, 0)

        assertThat(finished.status).isEqualTo(JobRunStatus.SUCCESS)
        assertThat(finished.summary).isEqualTo("rows=9")
        assertThat(page.runs).containsExactly(finished)
        assertThat(page.totalCount).isEqualTo(1)
    }

    @Test
    fun `pages all job runs in deterministic newest first order`(): Unit = runBlocking {
        val first = adapter.finish(
            adapter.start("event-outbox-dispatch", JobTriggerType.SCHEDULED, null, "system").id,
            JobRunStatus.SUCCESS,
            "first",
            null,
            10,
        )
        val second = adapter.finish(
            adapter.start("question-schedule", JobTriggerType.SCHEDULED, null, "system").id,
            JobRunStatus.SUCCESS,
            "second",
            null,
            11,
        )
        val sharedStartedAt = Instant.parse("2026-08-23T00:00:00Z")
        setStartedAt(first.id, sharedStartedAt)
        setStartedAt(second.id, sharedStartedAt)

        val page = adapter.findRuns(jobName = null, runId = null, limit = 1, offset = 0)

        assertThat(page.runs.map { it.id }).containsExactly(second.id)
        assertThat(page.totalCount).isEqualTo(2)
    }

    @Test
    fun `pages scheduler snapshots before loading their latest runs`(): Unit = runBlocking {
        execute(
            """
            insert into scheduled_jobs (job_name, enabled, schedule_type, schedule_value, timeout_seconds) values
                ('maintenance-cleanup', true, 'CRON', '0 0 3 * * *', 300),
                ('question-schedule', true, 'FIXED_DELAY', '30s', 90),
                ('user-stats-refresh', false, 'CRON', '0 */5 * * * *', 600)
            """.trimIndent(),
        )
        val successfulRun = adapter.finish(
            adapter.start("question-schedule", JobTriggerType.SCHEDULED, null, "system").id,
            JobRunStatus.SUCCESS,
            "first success",
            null,
            10,
        )
        setStartedAt(successfulRun.id, Instant.parse("2026-01-01T00:00:00Z"))
        val latestFailedRun = adapter.finish(
            adapter.start("question-schedule", JobTriggerType.SCHEDULED, null, "system").id,
            JobRunStatus.FAILED,
            null,
            "newer failure",
            12,
        )
        // Matching timestamps exercise the deterministic id tie-breaker used by both indexes.
        setStartedAt(latestFailedRun.id, Instant.parse("2026-01-01T00:00:00Z"))

        val page = adapter.findSnapshotPage(limit = 1, offset = 1)
        val unboundedPage = adapter.findSnapshotPage(limit = Int.MAX_VALUE, offset = 0)

        assertThat(page.snapshots.map { it.jobName }).containsExactly("question-schedule")
        assertThat(page.snapshots.single().latestRun?.id).isEqualTo(latestFailedRun.id)
        assertThat(page.snapshots.single().latestRun?.status).isEqualTo(JobRunStatus.FAILED)
        assertThat(page.snapshots.single().lastSuccessfulRun?.id).isEqualTo(successfulRun.id)
        assertThat(page.snapshots.single().lastSuccessfulRun?.status).isEqualTo(JobRunStatus.SUCCESS)
        assertThat(page.totalCount).isEqualTo(3)
        assertThat(page.limit).isEqualTo(1)
        assertThat(page.offset).isEqualTo(1)
        assertThat(unboundedPage.snapshots.map { it.jobName })
            .containsExactly("maintenance-cleanup", "question-schedule", "user-stats-refresh")
        assertThat(unboundedPage.snapshots.single { it.jobName == "maintenance-cleanup" }.latestRun).isNull()
        assertThat(unboundedPage.snapshots.single { it.jobName == "question-schedule" }.latestRun?.id)
            .isEqualTo(latestFailedRun.id)
        assertThat(adapter.findExistingJobNames(listOf("question-schedule", "missing")))
            .containsExactly("question-schedule")
    }

    private suspend fun execute(sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }

    private suspend fun setStartedAt(runId: Long, startedAt: Instant) {
        client.sql("update scheduled_job_runs set started_at = :startedAt where id = :runId")
            .bind("startedAt", startedAt)
            .bind("runId", runId)
            .fetch()
            .rowsUpdated()
            .awaitSingle()
    }
}
