apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: buddystuddy

resources:
  - namespace.yaml
  - config/backend-config.yaml
  - postgres/postgres.yaml
  - redis/redis.yaml
  - libretranslate/libretranslate.yaml
  - backend/backend.yaml
  - admin-frontend/admin-frontend.yaml
  - backup/postgres-backup.yaml

commonLabels:
  app.kubernetes.io/part-of: buddystuddy
