apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: buddystudy

resources:
  - namespace.yaml
  - config/backend-config.yaml
  - mysql/mysql.yaml
  - redis/redis.yaml
  - libretranslate/libretranslate.yaml
  - backend/backend.yaml
  - backup/mysql-backup.yaml

commonLabels:
  app.kubernetes.io/part-of: buddystudy
