create table redis_event_outbox (
    id bigint generated by default as identity primary key,
    event_id varchar(120) not null,
    event_type varchar(64) not null,
    payload_version integer not null default 1,
    payload_json clob not null,
    status varchar(20) not null default 'PENDING',
    attempts integer not null default 0,
    next_attempt_at timestamp not null,
    claimed_at timestamp,
    published_at timestamp,
    last_error clob,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uq_redis_event_outbox_type_event unique (event_type, event_id)
);
