package com.buddystudy.backend.common.adapter.inbound.web

import com.buddystudy.backend.config.BuddyStudyProperties
import io.r2dbc.spi.ConnectionFactories
import kotlinx.coroutines.reactive.awaitSingle
import kotlinx.coroutines.runBlocking
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.mockito.Mockito.mock
import org.mockito.Mockito.`when`
import org.springframework.data.redis.connection.ReactiveRedisConnection
import org.springframework.data.redis.connection.ReactiveRedisConnectionFactory
import org.springframework.r2dbc.core.DatabaseClient
import reactor.core.publisher.Mono
import java.time.Instant

class ReadinessCheckerTest {
    @Test
    fun `dependency check uses r2dbc and excludes scheduler state`(): Unit = runBlocking {
        val client = client("dependencies")
        val result = checker(client, monitoredJobs = listOf("missing-job")).check(includeScheduler = false)

        assertThat(result.ok).isTrue()
        assertThat(result.checks).containsOnlyKeys("database", "redis")
    }

    @Test
    fun `scheduler check reports a missing configured job`(): Unit = runBlocking {
        val client = client("missing")
        createSchedulerSchema(client)

        val result = checker(client, monitoredJobs = listOf("question-schedule")).check()

        assertThat(result.ok).isFalse()
        assertThat(result.checks.getValue("scheduler").message).contains("Missing monitored scheduler jobs")
    }

    @Test
    fun `scheduler check accepts a recent successful job`(): Unit = runBlocking {
        val client = client("success")
        createSchedulerSchema(client)
        execute(client, "insert into scheduled_jobs (job_name, enabled, timeout_seconds) values ('question-schedule', true, 300)")
        client.sql(
            "insert into scheduled_job_runs (job_name, status, started_at, error_message) values (:jobName, 'SUCCESS', :startedAt, null)",
        ).bind("jobName", "question-schedule").bind("startedAt", Instant.now()).fetch().rowsUpdated().awaitSingle()

        val result = checker(client, monitoredJobs = listOf("question-schedule")).check()

        assertThat(result.ok).isTrue()
        assertThat(result.checks.getValue("scheduler").ok).isTrue()
    }

    private fun checker(client: DatabaseClient, monitoredJobs: List<String>) = ReadinessChecker(
        client,
        healthyRedis(),
        BuddyStudyProperties(
            monitoring = BuddyStudyProperties.Monitoring(
                schedulerReadinessEnabled = true,
                schedulerMonitoredJobs = monitoredJobs,
                schedulerStartupGraceMinutes = 15,
                schedulerStaleThresholdMinutes = 15,
            ),
        ),
    )

    private fun client(name: String) = DatabaseClient.create(
        ConnectionFactories.get("r2dbc:h2:mem:///$name;MODE=PostgreSQL;DB_CLOSE_DELAY=-1"),
    )

    private suspend fun createSchedulerSchema(client: DatabaseClient) {
        execute(
            client,
            "create table scheduled_jobs (job_name varchar(120) primary key, enabled boolean not null, timeout_seconds integer not null)",
        )
        execute(
            client,
            "create table scheduled_job_runs (id bigint generated by default as identity primary key, job_name varchar(120) not null, status varchar(30) not null, started_at timestamp with time zone not null, error_message varchar(1000))",
        )
    }

    private suspend fun execute(client: DatabaseClient, sql: String) {
        client.sql(sql).fetch().rowsUpdated().awaitSingle()
    }

    private fun healthyRedis(): ReactiveRedisConnectionFactory {
        val redis = mock(ReactiveRedisConnectionFactory::class.java)
        val connection = mock(ReactiveRedisConnection::class.java)
        `when`(redis.reactiveConnection).thenReturn(connection)
        `when`(connection.ping()).thenReturn(Mono.just("PONG"))
        `when`(connection.closeLater()).thenReturn(Mono.empty())
        return redis
    }
}
